### ISSUE TITLE
Incorrect result

### ISSUE THREAD

**Issue by swarupbhc** [AlShakib/InternetSpeedMeter#14]
It's showing more speed than actual, please check.

![Screenshot from 2022-11-12 16-08-32](https://user-images.githubusercontent.com/55395995/201470346-24dc7890-053b-47b9-8a5a-e5c6b778367d.png)

**Comment by AlShakib** [comment]
Can't reproduce. Extension shows total (upload + download) speed on the shell but that speed tester is showing only upload or download on that screenshot.
Also, extension calculates total packet pass through your LAN or WiFi per second. Sometimes it wouldn't match with speed test results because you might have extra packet sending to or receiving  from your router or isp or other intermediary devices between you and the server that is sending you those test results.
